# Generated by Django 4.1.2 on 2022-11-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_owner_alter_entry_id_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
