# Generated by Django 4.1.2 on 2022-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lession'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
