# Generated by Django 4.1.2 on 2022-11-02 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
