# Generated by Django 4.1.2 on 2022-11-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_topic_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lession',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
