# Generated by Django 4.1.2 on 2022-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_lession_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
