# Generated by Django 4.1.2 on 2022-11-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_entry_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='owner',
            new_name='entry_owner',
        ),
    ]
