# Generated by Django 4.1.2 on 2022-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_owner_entry_entry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_owner',
            field=models.TextField(),
        ),
    ]
